// Generated file do not edit, generated by io.requery.processor.EntityProcessor
package requery.person.personEntity;

import io.requery.Entity;
import io.requery.ForeignKey;
import io.requery.Key;
import io.requery.ReferentialAction;
import io.requery.Table;
import java.io.Serializable;
import java.lang.Integer;
import javax.annotation.Generated;

@Entity(
        model = "personEntity",
        stateless = false
)
@Table(
        name = "Groups_Person"
)
@Generated("io.requery.processor.EntityProcessor")
public abstract class AbstractGroupEntity_PersonEntity implements Serializable {
    @ForeignKey(
            delete = ReferentialAction.CASCADE,
            update = ReferentialAction.CASCADE,
            references = requery.person.personEntity.GroupEntity.class
    )
    @Key
    protected Integer personId;

    @ForeignKey(
            delete = ReferentialAction.CASCADE,
            update = ReferentialAction.CASCADE,
            references = requery.person.personEntity.PersonEntity.class
    )
    @Key
    protected Integer groupId;
}
