// Generated file do not edit, generated by io.requery.processor.EntityProcessor
package requery.person.personEntity;

import io.requery.Persistable;
import io.requery.proxy.EntityProxy;
import io.requery.proxy.PropertyState;
import java.lang.Override;
import javax.annotation.Generated;

@Generated("io.requery.processor.EntityProcessor")
public class AddressEntity_CoordinateEntity implements Coordinate, Persistable {
    protected PropertyState $latitude_state;

    protected PropertyState $longitude_state;

    protected float latitude;

    protected float longitude;

    private final transient EntityProxy<AddressEntity> $proxy;

    public AddressEntity_CoordinateEntity(EntityProxy<AddressEntity> proxy) {
        this.$proxy = proxy;
    }

    @Override
    public float getLatitude() {
        return $proxy.get(requery.person.personEntity.AddressEntity.LATITUDE);
    }

    public void setLatitude(float latitude) {
        $proxy.set(requery.person.personEntity.AddressEntity.LATITUDE, latitude);
    }

    @Override
    public float getLongitude() {
        return $proxy.get(requery.person.personEntity.AddressEntity.LONGITUDE);
    }

    public void setLongitude(float longitude) {
        $proxy.set(requery.person.personEntity.AddressEntity.LONGITUDE, longitude);
    }
}
