// Generated file do not edit, generated by io.requery.processor.EntityProcessor
package requery.person.entity;

import io.requery.*;

import javax.annotation.Generated;
import java.io.Serializable;

@Entity(
        model = "requery/person/entity"
)
@Table(
        name = "Groups_Person"
)
@Generated("io.requery.processor.EntityProcessor")
public abstract class AbstractGroupEntity_PersonEntity implements Serializable {
    @ForeignKey(
            delete = ReferentialAction.CASCADE,
            update = ReferentialAction.CASCADE,
            references = GroupEntity.class
    )
    @Key
    protected Integer personId;

    @ForeignKey(
            delete = ReferentialAction.CASCADE,
            update = ReferentialAction.CASCADE,
            references = PersonEntity.class
    )
    @Key
    protected Integer groupId;
}
